### ISSUE TITLE
Installer caching UX 

### ISSUE THREAD

**Issue by sebastius** [badgeteam/HackerHotel-2019-esp32-firmware#34]
Knopje indrukken om alles te updaten is onhandig, het is niet heel duidelijk dat er een update is voor je. Misschien een soort 'laatste update tijd' meezenden dat ie dat checkt en je dan aanbiedt om te updaten? Gaat wel lekker snel maar is ook wat meer behulpzaam.

**Comment by renzenicolai** [comment]
Goed idee. Ik ga er mee bezig!
